README.md
Touch up readme information 
Introduction
Disclaimer
Contact info
=> added introduction, disclaimer, and contact info to README.md

server/models/Card.js, server/models/Deck.js, server/models/User.js, server/models/index.js, server/schemas/index.js
Created basic models to get started:
- card
- user
- deck
=> Model setup

server/models/User.js, server/schemas/typeDefs.js
Setup initial typedefs for models
- user
- card
- deck
=> initial typedefs defined

client/package-lock.json, client/package.json, package-lock.json, package.json, server/package-lock.json, server/package.json
Added initial dependencies for dev
=> added initial modules

client/src/utils/queries.js, server/package.json, server/seeders/cardSeeds.json, server/seeders/cleanDB.js, server/seeders/deckSeeds.json, server/seeders/seed.js
Created small sample seed files for one deck and several cards. Fixed the seed.js file issue "deck is not defined". There is not currently a relationship between the cards and the deck.
Test:
=> Seeder setup

server/models/Card.js, server/schemas/typeDefs.js
Added field "suit" to card schema and typedefs.
=> Added needed field to card schema

README.md
created temporary license information reserving all rights to our project and code
=> Temporary license placeholder

client/src/utils/queries.js, server/schemas/resolvers.js, server/schemas/typeDefs.js
Completed deck queries:
1. allDecks
2. oneDeck
Test:
=> Deck Queries

server/models/Spread.js, server/models/index.js, server/schemas/typeDefs.js, server/seeders/seed.js, server/seeders/spreadSeeds.json
Added spread model and seed data
Tests:
=> Added Spread model

server/models/Reading.js, server/models/Spread.js, server/models/index.js, server/schemas/typeDefs.js, server/seeders/seed.js, server/seeders/spreadSeeds.json
Added a model for `Reading` objects.
=> Add model `Reading`

server/models/Card.js, server/models/Reading.js, server/models/Spread.js, server/models/index.js, server/schemas/typeDefs.js, server/seeders/seed.js, server/seeders/spreadSeeds.json
Added a field to the card object for a card description.
Test:
=> Card object update

client/src/main.jsx, client/src/pages/Error.jsx, package-lock.json, package.json
-Added router to main.jsx, linking pages to app
-Added error.jsx to pages
=> added router structure to main.jsx file and added error.jsx page

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/components/Header.jsx, client/src/index.css, client/src/main.jsx, client/src/pages/Home.jsx, package-lock.json, package.json
-Added simple header component with login and sign up buttons, no forms attached yet
-Added content to home.jsx and app.jsx
-Added tailwindcss to dependencies
=> added header content, error content, home content, updated app.jsx

client/src/components/Authentication/LoginForm.jsx, client/src/components/Header.jsx, client/src/index.css, client/src/main.jsx, client/src/pages/Login.jsx, client/tailwind.config.js
-Added LoginForm component
-Added content to login page, very basic, not styled or tied to the backend content yet
-Added tailwind.config file, still need to configure properly
=> added content to login files

client/package-lock.json, client/package.json, client/src/components/CardDrawing/Card.jsx, client/src/index.css, client/src/pages/Home.jsx, package-lock.json, package.json
-Created card.jsx component, added it to home.jsx
-Added a fonts folder, included Amarante.ttf file, open to suggestions if another font is preferred
=> Card-component 

server/models/Spread.js, server/schemas/typeDefs.js
Added fields to spread model and typedefs:
Remove field from spread model and typedefs:
=> Update Spread Model

server/models/Deck.js, server/models/Spread.js, server/schemas/typeDefs.js
Added fields to deck model and typedef:
remove field from deck model and typedef:
=> Update Deck Model

server/models/Card.js, server/models/Deck.js, server/models/Spread.js, server/schemas/typeDefs.js
Add fields to card model and typedef:
remove field from card model and typedef:
=> New Update Card Model

server/models/Card.js, server/models/Deck.js, server/models/Reading.js, server/models/Spread.js, server/schemas/typeDefs.js
Added subdocument to reading(cards) model and typedef:
Added commented out date field to finish in the near future. We will need to create a date scalar to use with QGL. There are multiple places we want to keep dates and GQL does not inherently have a date type.
The typedefs refer to appropriate type created for the cards subdocument.
=> Update Reading Model

client/src/components/Authentication/SignUpModal.jsx
-Added username field to signup modal
=> added username field to signup

client/src/main.jsx, package-lock.json
-Added apollo client and provider to the main.jsx
=> added apollo server/client to main.jsx

client/src/components/Authentication/LoginModal.jsx, client/src/components/Authentication/SignUpForm.jsx, client/src/components/Authentication/SignUpModal.jsx, client/src/components/Navbar.jsx, client/src/main.jsx, client/src/utils/auth.js, client/src/utils/mutations.js
Changed Multiple files, and after a long daring, happy adventure, it works! :)
=> Front end mutations

client/src/components/Authentication/LoginForm.jsx, client/src/components/Authentication/LoginModal.jsx
-Moved login form to be it's own component
-Added mutations and props to login modal, is functional
=> updated login form and modals, is functional

client/src/components/Authentication/LoginForm.jsx, client/src/components/Authentication/LoginModal.jsx, client/src/components/Authentication/SignUpForm.jsx, client/src/components/Authentication/SignUpModal.jsx, client/src/index.css
-Added close buttons to modals
-Cleaned up file structure
=> added close button to modals

client/src/utils/mutations.js, server/schemas/resolvers.js, server/schemas/typeDefs.js
Added mutations to typedefs, resolvers, and mutations.js
Added common logic to resolvers
=> Edit User Mutations

client/src/components/Authentication/SignUpForm.jsx, package-lock.json, package.json, server/schemas/resolvers.js
Using AuthenticationError requires module. Updated package files and imported requirements in resolvers file
=> installed needed packages for authentication error from appollo

server/schemas/resolvers.js, server/schemas/typeDefs.js
Cleaned up resolvers
- Changed 'parent' to '_'
- Changed 'args' to '__'
Allows for easier to read code without distracting those with props we are not using
=> Resolvers cleanup

server/schemas/resolvers.js, server/schemas/typeDefs.js
Users may now delete themselves. A message is displayed that the user is deleted using typedefs
=> User can now delete self. Updated Type Defs and resolvers

server/schemas/resolvers.js
added auth check to add deck and add reading for users.
=> add auth check to user mutations add deck and add reading

server/schemas/resolvers.js
Minor fix to add reading to user mutation. Added second param to populate readings.
=> add param to reading mutation

client/src/components/Authentication/SignUp/SignUpForm.jsx
This allows user to view if their inputs in the signup form meet our requirements in real-time.
=> Added functionality for live feedback on signup form

client/src/components/Authentication/SignUp/SignUpForm.jsx
-Added a checkbox to sign up form, requiring user to read terms and place check upon agreeing
-Added link to Terms page
=> added checkbox to signup form for terms

client/src/components/CardDrawing/CardBack.jsx, client/src/components/CardDrawing/CardFront.jsx, client/src/components/Footer.jsx, client/src/main.jsx, client/src/pages/Reading.jsx, server/server.js
-Added a basic shell for the Reading page, updating the main.jsx file and footer (temporary)
-Added a CardBack file that will receive card images
-Modified CardDrawing folder, updating file names
=> added reading page, renamed files

client/src/utils/mutations.js, server/schemas/resolvers.js, server/schemas/typeDefs.js
**Description**:
This PR introduces a new mutation to update reading user notes in the TarotDeck application.
**Changes Made:**
- Created a new `UpdateReadingNotesInput` type in the typedefs to specify the input for updating reading user notes.
- Added a new resolver function `updateReadingNotes` to handle the mutation logic.
- Updated the resolvers file to include the new mutation resolver.
- Tested the mutation in the Apollo Sandbox to verify its functionality.
**Testing**:
- Tested the updateReadingUserNotes mutation in the Apollo Sandbox.
- Verified that the mutation updates the reading user notes as expected.
=> Feature: Added mutation to update reading user notes

server/models/Reading.js, server/schemas/resolvers.js
This pull request introduces a fix for the `allReadingsByUser` query.
**Issue:**
- card name field populates as null
- note title populates as null
**Changes:**
- updated `allReadingsByUser` resolver to include appropriate path to populate card names from the associated card objects
- updated `allReadingsByUser` resolver to include appropriate path to populate not titles from the associated card objects
- updated `Reading` model to remove array from `userNotes` field
**Test:**
- Tested new code on multiple users with multiple readings in Apollo sandbox 
- Verified db info through Compass
=> fixed issue of null values

client/src/utils/queries.js, server/seeders/deckSeeds.json
update seed file and queries file to use the proper deck field name "deckDescription"
=> Fix conflict with Deck field "deckDescription"

client/src/components/Authentication/SignUp/SignUpForm.jsx, client/src/utils/auth.js
User is now redirected to their Profile page
=> Redirects user to profile after signup and login.

client/src/utils/auth.js
Changed the location when logging in and signing up to be directed to Home instead of Profile
=> Changed login/signup location

client/src/utils/mutations.js, debug.log, server/schemas/resolvers.js, server/schemas/typeDefs.js
- Added common error handling logic to resolvers without existing error handling.
- Refactored existing error handling to use common logic where applicable.
- Introduced helper functions for common error handling tasks.
- refactored/reordered `updateObject`, `updateObjectArrays`, `checkAuthentication`, and `handleNotFound` helper functions to `resolvers.js`.
- Refactored resolvers to use common error handling functions where applicable.
- Ensured consistent error messages and handling across resolvers.
- Improve code maintainability by reducing duplication of error handling logic.
- Enhance readability of resolver functions by using common error handling patterns.
- Ensure consistent error messages and behavior across the application.
- Improved error handling and consistency in resolver …
=> Error Handling Enhancements

client/src/components/Headers/Header.jsx, client/src/components/Hero/HeroOne/HeroOne.jsx, client/src/components/Navbar.jsx, client/src/pages/Home/Home.jsx, client/src/pages/Reading.jsx
Additions:
-Added Header.css file, still need to fill it with CSS properties
-Added Header.jsx file, will display on pages outside of the landing page
-Added Header.jsx file to Home page and Reading page (still need to resolve alignment)
Changes: 
-Removed commented out code on HeroOne.jsx
-Modified the navbar by adding UseEffect to change margin and positions of the navbar items upon logging in and signing out (Still working on exact positioning. (Logout will change when adding all content to populate list under the profile drawer)
=> Added header, navbar functionality

server/models/User.js, server/schemas/resolvers.js
This PR enhances the `updateObject` function in the resolvers to enforce validation checks before updating an object and allows bypassing required fields. Additionally, the `birthday` field has been added back to the user model.
- Modified the `updateObject` function to include validation checks using Mongoose validators before updating an object.
- Added the `birthday` field back to the user model.
Thorough testing was conducted in the Apollo Sandbox:
1. Each field was updated individually to ensure that it would update correctly.
2. All fields were updated together to confirm that they would update simultaneously.
3. Invalid data was entered to verify that the function would reject it.
N/A
- Updated the `updateObject` function to include validation checks.
- Added the `birthday` field …
=> Enhanced Object Updating and Schema Update for User Model

client/src/components/Reading/GettingStarted.jsx, client/src/pages/Reading.jsx, client/src/utils/mutations.js, server/models/User.js, server/schemas/typeDefs.js
This arithmetic retrieves the user's ID and submits a mutation request to update the user's profile information based on their form.  The form consists of updates for the user's Full Name, Birthday, and Phone Number. These updates are not mandatory and may be skipped.
I added functionality for the user to view their birthday and phone number format in live time. They do not have to input '(', ')', '-', or '/' characters in order to write their information. Nor do they have to click on a calender or a drop-down menu. However, there may be functionality in the future to have a drop-down menu/calender in the future as well.
This current system only allows America phone numbers, but will be updated in the future. 
There is also checks to make sure the user inputs the information in the …
=> Set up arithmetic for users to update their profile

client/src/components/Drawer/Drawer.css, client/src/components/Drawer/Drawer.jsx, client/src/components/HamburgerIcon.jsx, client/src/components/Navbar.jsx, client/src/index.css, client/src/main.jsx, client/src/pages/FAQ.jsx, client/src/pages/Profile.jsx, client/src/pages/Reading.jsx, client/src/pages/Settings.jsx, client/src/pages/Support.jsx
Additions: 
-Added hamburger menu button to open up drawer and changed color of text to note which page is selected on Drawer.jsx 
-Added additional paths Profile, Settings, FAQs, and Support on Navbar.jsx, for when drawer is open. Paths are hidden when drawer is collapsed
-Added paths for Settings, Support, and FAQs on main.jsx
-Added FAQ page and initial content on FAQ.jsx
-Added Settings page and initial content on Settings.jsx
-Added Support page and initial content on Support.jsx
Modifications:
-Modified styling properties on Drawer.css
-Minor formatting changes on index.css
-Modified initial content on Profile.jsx
-Minor formatting on Reading.jsx
Changes to come: 
-Need to fix the drawer from opening when clicking on icons on Drawer.jsx
-Will remove HamburgerIcon.jsx file as it is …
=> udpated drawer and added additional links

server/models/User.js, server/schemas/resolvers.js, server/schemas/typeDefs.js
This PR enhances the security and functionality of the user authentication and profile management features. The key changes include:
- Updated the password validation regex to disallow spaces and ensure that passwords are between 8 and 25 characters long, including at least one uppercase letter, one lowercase letter, one number, and one special character.
- Modified the `updateUserPassword` mutation to validate the current password before allowing the update. The mutation now ensures that the user is authenticated and the current password is correct before updating the password to a new value.
These changes enhance the security of user accounts and improve the user experience by ensuring that updates to sensitive information require proper authentication and validation. …
=> Add Password Validation and Security Improvements

client/src/index.css, client/src/pages/Landing/IconDescriptions/CardsDesc.jsx, client/src/pages/Landing/IconDescriptions/DashboardDesc.jsx, client/src/pages/Landing/IconDescriptions/HandsDesc.jsx, client/src/pages/Landing/IconDescriptions/StoreDesc.jsx, client/src/pages/Landing/ImageGrid.jsx, client/src/pages/Landing/Landing.css, client/src/pages/Landing/Landing.jsx, client/src/pages/Landing/PanelCarousel.jsx, client/src/pages/Landing/PanelOne.jsx, client/src/pages/Landing/PanelThree.jsx, client/src/pages/Landing/PanelTwo.jsx
Description: 
Added more content to each panel of the landing page and added vertical panel stepper. 
Additions: 
-Added an vertical panel stepper to the PanelCarousel.jsx file
-Added star overlay to each of the Panels in the carousel on the landing page
Modifications: 
-Changed text shadow on index.css
-Updated descriptions for the Readings (CardsDesc), Dashboard (DashboardDesc), Community (HandsDesc), and Store (StoreDesc), making each an <ul> with <li> items
-Modified ImageGrid.jsx to include spread descriptions, replacing previous h2 text below image grid
-Updated Landing.css to reflect styling changes to all components in the Landing folder
=> Fixed image grid and descriptions, added content to panel3, and added vertical stepper

client/src/components/NavigationPane/NaviationLinks.jsx
Fixed logout button in navlinks
=> Fixed logout button in navlinks

client/src/pages/Dashboard/DashboardLeft.jsx, client/src/utils/queries.js, server/schemas/resolvers.js, server/schemas/typeDefs.js, server/seeders/seed.js, server/server.js
Created new Queries that allows the App to gather information based on the User's 
- _id
- Decks
- Favorite Decks
- Favorite Spreads
Multiple files were changed to make this happen. Seed.js and server.js were do the letting.
=> Dashboard data retrieval

client/src/components/NavigationPane/NaviationLinks.jsx, client/src/components/NavigationPane/NavigationIcons.jsx, server/utils/auth.js
Previously prevented users from logging in due to errors. Also prevented the user from logging out due to commented out logout.
=> Fixed login and logout bug

client/src/pages/Settings/SettingsLeft.jsx
Overview:
This pull request enhances the reset password functionality by integrating it with the EDIT_USER_PASSWORD mutation. Now, when a user submits the reset password form, their new password data is seamlessly sent to the server for processing.
Changes Made:
- Integrated the EDIT_USER_PASSWORD mutation into the reset password form submission process.
- Utilized the user-entered data from the form to update the password on the server.
- Ensured proper error handling and feedback messages for invalid inputs
=> Allows user to Reset Password

client/src/pages/Settings/SettingsLeft/EmailReset.jsx, client/src/pages/Settings/SettingsLeft/PasswordReset.jsx, client/src/pages/Settings/SettingsLeft/SettingsLeft.jsx, client/src/utils/mutations.js
Overview:
This pull request focuses on the email update feature, enabling users to update their email addresses using a new email and their current password. Additionally, it acknowledges and highlights an existing issue related to email validation using regular expressions.
Changes Made:
- Implemented functionality allowing users to update their email addresses with a new email and current password.
- Existing Issue: Acknowledged the presence of a validation issue with the regular expression used for email validation. The issue with regex is apparent when there is no error after email@g but a new error comes after gmail. (on the period) until another letter is added. Example: josephpicardat (error), josephpicardat@ (error), josephpicardat@g (no error, josephpicardat@gmail. (error), …
=> Allows user to update Username. Noticed that the Regex has an issue

client/src/components/HeaderPane/LargeHeader.jsx, client/src/pages/Dashboard/Dashboard.css, client/src/pages/Dashboard/DashboardLeft.jsx, client/src/pages/Dashboard/DashboardRight.jsx
This request provides cleaner and less redundant code, removing inline CSS styling and adding it to a designated CSS file.
- Minor logo size adjustment to the large header component, will revisit later 
- Updated Dashboard.css with CSS content from the DashboardLeft.jsx and DashboardRight.jsx files, removing inline CSS properties
- [TDS-19](https://tarotdeck.atlassian.net/browse/TDS-19)
=> Refactor(CSS): Convert inline CSS to designated CSS [JIRA-TDS-19]

server/schemas/resolvers.js, server/schemas/typeDefs.js, server/server.js
This PR introduces functionality to query the S3 bucket for a single deck and updates the typedefs accordingly. This will enable us to fetch deck information directly from S3. We are still able to utilize GraphQL so the getDeck query can be found in the sandbox.
**PR Checklist:**
**Behavior:**
- currently not applicable
**Instructions for AWS Keys:**
1. Navigate to the AWS Secrets Manager in your AWS account.
2. Retrieve your AWS access keys and secret keys.
3. Add the following variables to your `.env` file:
```env
AWS_ACCESS_KEY_ID=(found in AWS secret manager)
AWS_SECRET_ACCESS_KEY=(found in AWS secret manager)
AWS_REGION=(found in AWS)
PORT=3001
NODE_ENV=development
```
**Code Implementation:**
```javascript
// …
```
=> Migration Code: S3 Deck Query Implementation

client/index.html, client/src/pages/Landing/Landing.css, client/src/pages/Landing/Landing.jsx, client/src/pages/Landing/Login_Signup/AuthComponent.jsx, client/src/pages/Landing/Login_Signup/LoginModal.jsx, client/src/pages/Landing/Login_Signup/SignUpModal.jsx, client/src/pages/Landing/ModalContext.jsx, client/src/pages/Landing/PanelCarousel.jsx, client/src/pages/Landing/PanelThree.jsx
**Landing Page Bug:**
Bug: Resolving locked login/signup modal & other landing page issues
This PR resolves the issue of the login/signup modal being locked. As well as the models being able to be closed when changing carousel indexes and formatting issues within index.html. 
[x] Code follows the project's coding standards.
[x] Jira tasks added to the project backlog to update documentation if necessary.
[x] Updated index.html to have the correct formatting as well as a title of "TarotDeck"
**Behavior:**
[ ] Users should be able to use the landing page as usual.
[ ] Users should be able to click the login/signup buttons and fill out the forms.
[ ] Users should be able to close the modal when pressing "ESC" and scrolling through …
=> fix(landing): resolved the login/signup modal on landing page [TDS-166]

client/src/components/AsidePane/QuickUserInfo/QuickUserInfo.jsx, client/src/utils/queries.js, server/models/User.js, server/schemas/typeDefs.js
**Title: QuickUserInfo**
Feature: User Data Present in QuickUserInfo
This PR introduces a live feed on their username, first name, date of account creation, and how many readings they have.
[x] Code follows the project's coding standards.
**Behavior:**
[ ] Users should see their username, first name, date of account creation, and how many readings they have.
[ ] If there is an update to their data, the data present in QuickUserInfo should update as well.
[ ] A query request was made only when an update happens to the user's data and/or the first time the user's account is created.
- TDS-174 [(https://tarotdeck.atlassian.net/browse/TDS-174)]
=> feat(userData): added user's data to QuickUserInfo [TDS-174]

client/src/pages/Settings/Settings.css, client/src/pages/Settings/SettingsRight/AvatarModal.jsx
This PR introduces adds additional styling and continuity to the avatar modal to match the rest of the app.
[x] Code follows the project's coding standards.
[ ] Jira tasks added in the project backlog to update documentation if necessary.
**Behavior:**
[x] When clicking on the avatar icon to the right of "Active Avatar", users should see a gallery of avatar options displayed 
in the UI.
[x] The display should have colors and fonts that match the rest of the app. 
[x] The shape of the avatar modal should be a tall rectangle, somewhat resembling the shape of a tarot card.
[x] Upon hovering over the avatars in …
=> Refactor(css):Avatar Modal CSS [TDS-199]

server/schemas/resolvers.js, server/schemas/typeDefs.js
This PR introduces the ability to fetch deck metadata and deck details from S3, updates the field names in the JSON files, and ensures the application can handle S3 queries dynamically.
**PR Checklist:**
**Behavior:**
- N/A
**Querying Process:**
1. **Index Files**:
- The S3 bucket contains index files (`DECK_index.json`) which hold limited information about each deck, such as the deck ID, name, image URL, and the path to the detailed deck objects.
2. **Fetching Index Data**:
- The `allDecks` query fetches the `DECK_index.json` file from the S3 bucket, providing an array of decks with limited metadata.
3. **Detailed Deck Data**:
- Each entry in the index file includes a `objectFileUrl` (now updated to …
=> Feature: S3 Metadata and Deck Details Integration

server/schemas/resolvers.js, server/schemas/typeDefs.js
This PR introduces the ability to fetch avatar metadata and avatar details from S3, updates the field names in the JSON files, and ensures the application can handle S3 queries dynamically.
**PR Checklist:**
**Behavior:**
- N/A
**Querying Process:**
1. **Index Files**:
- The S3 bucket contains index files (`AVAT_index.json`) which hold limited information about each avatar, such as the avatar ID, name, image URL, and the path to the detailed avatar objects.
2. **Fetching Index Data**:
- The `allAvatarss` query fetches the `AVAT_index.json` file from the S3 bucket, providing an array of avatars with limited metadata.
3. **Detailed Avatar Data**:
- Each entry in the index file includes a `objectFileUrl` (now updated …
=> Feature: S3 Metadata and Avatar Details Integration

awssdktest.js, client/src/pages/Settings/Settings.css, client/src/pages/Settings/SettingsLeft/UserInformation.jsx, server/models/User.js
**Pull Request Template**
**Title:**
Fix: User can delete data in Settings Form
This PR fixes the issue where a user can not delete certain form inputs like firstName or only input certain values and leave others blank. The PR also added a trashcan Icon for the user to delete certain fields. 
[x] The code formatter was run before submitting PR; changes were 
made before submitting the PR request if needed.
**Behavior:**
[ ] Users should see a delete icon next to certain form inputs
[ ] Users may leave inputs blank in the form
- TDS-195 [https://tarotdeck.atlassian.net/browse/TDS-195]
=> User Can Delete Data in Setting Form

client/src/pages/Settings/Settings.css, client/src/pages/Settings/SettingsLeft/UserInformation.jsx
**Title:**
Fix: User Information Styling Issues
This PR fixes the issue of incorrect styling and poor styling choices made in a prior PR. The user can delete most of their information stored in the database while keeping others.
**Behavior:**
[ ] Users should be able to delete some desired information inside their settings
**Screenshots/GIFs:**
=> fix(userInformation): fixed styling issues

client/src/pages/Dashboard/AltCarousel.jsx, client/src/pages/Dashboard/Dashboard.css, client/src/pages/Dashboard/DashboardLeft.jsx, client/src/pages/Dashboard/DashboardRight.jsx, client/src/pages/Dashboard/UniversalCarousel.jsx, client/src/pages/Settings/SettingsLeft/UserInformation.jsx
This PR addresses the issues I encountered with the previous pagination dots skipping and not properly coinciding with the selected image. It also resolves the issue of the spread images overlapping and not having appropriate margin. This process included moving away from the original splide component that I brought in, as I was having issues with flex properties and found it easier to rebuild. There are some future proofing items left in the css. There are arrows currently hidden, but as we continue to add more decks and spreads, if we would prefer to add them over the pagination dots, they are easily accessible. 
[x] The code formatter was run before submitting PR, and if needed, changes …
=> Splide Component and Margin Issues on Dashboard

client/src/pages/BrowseSpreads/BrowseSpreads.css, client/src/pages/BrowseSpreads/BrowseSpreads.jsx, client/src/pages/BrowseSpreads/SpreadModal.jsx, client/src/pages/Settings/SettingsLeft/UserInformation.jsx
**Title:**
Feature: Avatar Selection
This PR introduces a skeleton code for browse spreads.
[x] The code formatter was run before submitting PR; if needed, changes were 
[x] Jira tasks added in the project backlog to update documentation if 
necessary.
[x] 
**Behavior:**
[ ] Users should see an outline of browse spreads
[ ] Users can click on bottom spreads to open and close modal
- TDS-232[https://tarotdeck.atlassian.net/browse/TDS-232]
**Screenshots/GIFs:**
=> feat(browse_spreads): updated the page with skeleton code [TDS-232]

client/index.html, client/src/components/NavigationPane/NavigationIcons.jsx, client/src/components/NavigationPane/NavigationPane.css, client/src/pages/Settings/SettingsLeft/UserInformation.jsx
**Title:**
Refactor: Nav Pane Icon Fixes
This PR fixes the margin issues among the icons in the NavigationIcons file and removes excess/old code that is no longer needed. 
[x] Jira tasks added in the project backlog to update documentation if 
necessary.
**Behavior:**
[ ] Users should see an evenly spaced navigation icon menu when logged in
[ ] In NavigationIcons.jsx, margins have been adjusted icon images using Inline-CSS
[ ] Unnecessary classNames were removed, minor formatting changes were made, and old code was …
=> Refactor(icons-css): Nav pane icon fixes [TDS-209]

client/src/pages/BrowseDecks/BrowseDecks.css, client/src/pages/BrowseDecks/BrowseDecks.jsx, client/src/pages/BrowseDecks/DecksModal.jsx
**Title:**
Feature: Browse Decks Skeleton Code
This PR introduces new functionality to the Browse Decks page. The user may view the featured deck, and 3 available decks, and open a modal for each deck. 
[x] The code formatter was run before submitting PR; if needed, changes were 
[ ] Jira tasks added in the project backlog to update documentation if 
necessary.
**Behavior:**
[ ] Users should see a page showing off different decks
[ ] Upon clicking on a deck, the user opens a modal giving random information about the deck
- [TDS-235](https://tarotdeck.atlassian.net/browse/TDS-235)
**Screenshots/GIFs:**
=> feat(BrowseDecks): skeleton code to BrowseDecks

client/src/pages/BrowseDecks/BrowseDecks.css, client/src/pages/BrowseDecks/BrowseDecks.jsx, client/src/pages/BrowseDecks/DecksModal.jsx, client/src/utils/queries.js
**Title:**
Feature: Browse Decks
This PR introduces the ability for users to view all available decks and retrieve info on each of them when opening the modal.
[x] The code formatter was run before submitting PR; if needed, changes were 
[ ] Jira tasks added in the project backlog to update documentation if 
necessary.
[ ] (add any other checklist items discussed in sprint planning or subtasks in 
story)
**Behavior:**
[ ] Users should see all available decks
[ ] Upon selecting a card, it opens a modal to learn more
- [TDS-152](https://tarotdeck.atlassian.net/browse/TDS-152)
**Screenshots/GIFs:**
=> feat(BrowseDecks): Added data to the decks [TDS-152]

client/src/pages/Settings/SettingsLeft/UserInformation.jsx, client/src/pages/Settings/SettingsRight/AdvancedSecurity.jsx, client/src/pages/Settings/SettingsRight/CookiesSettings.jsx, client/src/pages/Settings/SettingsRight/Notifications.jsx, client/src/pages/Settings/SettingsRight/SubmitSettingsRight.jsx, client/src/utils/mutations.js, client/src/utils/queries.js
**Title:**
Fix Toggles in Settings Page
This PR fixes the toggles that break the site. It also is connected to the backend.
[ ] Jira tasks added in the project backlog to update documentation if 
necessary.
**Behavior:**
[ ] Users should be able to update their toggle preferences.
[ ] Database should update after the user updates the toggle
- [TDS-253](https://tarotdeck.atlassian.net/browse/TDS-253)
=> fix(Right_Side_Toggles): fixed toggles from breaking site

client/src/pages/Settings/SettingsRight/AvatarModal.jsx
**Title:**
Fix: Avatar Selection
This PR fixes the Avatar Selection.
[x] Jira tasks added in the project backlog to update documentation if 
necessary.
**Behavior:**
[ ] Users should be able to update their avatar
[ ] A successful User mutation
- [TDS-284](https://tarotdeck.atlassian.net/browse/TDS-284)
=> fix(AvatarSelection): Avatar Selection Saves Avatar Choice

client/src/pages/Settings/FormatedFunctions/FormatedFunctions.jsx, client/src/pages/Settings/SettingsLeft/UserInformation.jsx
Title:
Fix: Birthday Error
Description:
This PR fixes the issue when a user saves their birthday and it subtracts a day.
[x] The code formatter was run before submitting PR, and if needed, changes were
[x] Jira tasks added in the project backlog to update documentation if
necessary.
Behavior:
User Side Behavior:
[ ] Users should be able to update their birthday accurately
Developer Side Behavior:
[ ] A successful User mutation
Jira Tasks:
[TDS-283](https://tarotdeck.atlassian.net/browse/TDS-283)
=> fix(birthday): Updated Birthday will keep the same day

client/src/pages/Settings/SettingsLeft/UserInformation.jsx
**Title:**
Fix: UserInformation Form Submit Caused Refresh
This PR fixes the refresh that takes place when a user update's their information in settings
[x] Jira tasks added in the project backlog to update documentation if 
necessary.
**Behavior:**
[ ] Users should update their information without triggering a page refresh
- [TDS-285](https://tarotdeck.atlassian.net/browse/TDS-285)
=> fix(UserInformation): Form Submit doesn't refresh page

client/src/components/AsidePane/QuickUserInfo/QuickUserInfo.jsx, client/src/components/HeaderPane/LargeHeader.jsx, client/src/components/HeaderPane/SimpleHeader.jsx, client/src/pages/Settings/SettingsRight/Appearance.jsx, client/src/pages/Settings/SettingsRight/AvatarModal.jsx, client/src/utils/queries.js, server/models/Avatar.js, server/schemas/typeDefs.js
**Description:**  
This PR implements the addition of two separate URL fields for user avatars: `circleImageUrl` and `squareImageUrl`. The following components have been updated accordingly:
- Headers, settings page, and avatar selection menu now use `circleImageUrl`.
- The quick user info pane now uses `squareImageUrl`.
Additionally, a note has been added regarding the upcoming refactor needed for the shop page to handle separate avatar and deck images.
---
**PR Checklist:**  
---
**Behavior Checklist:**
**User-side behavior:**
**Dev-side behavior:**
---
**Jira Tasks:**  
Link to related Jira task:  
- [TDS-275](https://tarotdeck.atlassian.net/browse/TDS-275) Refactor Avatar Display in User Info Pane, Settings Page, and Headers
---
**Background Context:**  
Previously, avatars were saved …
=> Add Circle and Square Avatar Support in Database and UI Components

server/config/connection.js, server/models/NewUserDefaults.js, server/schemas/resolvers.js, server/schemas/typeDefs.js
**Title:**
Feature: New User Default Data
This PR gives new users default values including avatars, decks, themes, and more all from the database. A future update will be needed to dynamically update what _ids new users will get and how to update old users on new _ids.
[ ] Jira tasks added in the project backlog to update documentation if 
necessary.
**Behavior:**
[x] Users should see that they have default data pertaining to the theme and more.
[x] New users will be given data based off of the NewUserDefaults …
=> feat(NewUserSchema): New users will have certain default values

client/src/components/SpreadLayouts/OneCardCenter.jsx, client/src/components/SpreadLayouts/SixSpokesUpright.jsx, client/src/components/SpreadLayouts/SpreadLayouts.css, client/src/components/SpreadLayouts/ThreeCardHorizontal.jsx, client/src/components/SpreadLayouts/sixSpokesUpright.css, client/src/pages/NewReading/NewReading.jsx
**Description**:  
This PR introduces a feature allowing users to reveal cards one at a time by clicking a "Reveal Next Card" button on the reading page. The changes are designed to enhance user interactivity and pacing, making the reading experience more immersive.
The feature:
- Uses a `cardRefs` array with `useRef` to track each card's flip status.
- Updates card visibility sequentially, ensuring only one card is revealed per button click.
- Works across different spread layouts, including OneCardCenter, ThreeCardHorizontal, and SixSpokesUpright.
**PR Checklist**:
**Behavior**:
_User Side_:
_Developer Side_:
**Jira Tasks**:
- [TDS-290](https://tarotdeck.atlassian.net/browse/TDS-290)
**Background Context**:
This feature aims to improve the user …
=> Implement Sequential Card Flipping with "Reveal Next Card" Button

client/src/pages/NewReading/NewReading.jsx
This PR replaces the separate buttons for starting, revealing, and saving the reading with a single button that updates dynamically based on the user’s reading progress. The button transitions smoothly through the stages of "Start Reading," "Reveal Next Card," and "Save Reading," resetting to "Start Reading" upon completion.
This change provides a more streamlined and intuitive user experience, allowing users to progress through a reading with minimal interface distractions.
**User Side Behavior:**
**Dev Side Behavior:**
[TDS-300](https://tarotdeck.atlassian.net/browse/TDS-300) – Update Button to Dynamically Change Based on Reading Stage
This update is part of an effort to improve the user experience by consolidating the reading button actions. By combining the three functions into a …
=> Consolidate Reading Actions into a Dynamic Button

client/index.html, client/src/pages/Loading/GlobalProvider.jsx
**Title: Loading Page Background Color FIx** 
**Description:** 
This PR fixes the bug where the loading page did not display the correct background color
** PR Checklist:** 
[x] Code follows the project's coding standards and conventions. 
[x] The code formatter was run before submitting PR, and if needed, changes were made before submitting the PR request. 
[x] Jira tasks added to the project backlog to update documentation if necessary. 
**Behavior:** 
- **User Side Behavior:** 
[  ] Users should see their theme color upon refresh. 
[  ] If it is a new user or they delete the theme in local storage, it will briefly display the 'main' background color but will update to the user's default theme upon loading. 
**Jira Tasks:** 
- [TDS-307](https://tarotdeck.atlassian.net/browse/TDS-307)
=> fix(loading_page): Loading page displays correct background color

client/src/components/AsidePane/ReadingAside.jsx, client/src/components/SpreadLayouts/OneCardCenter.jsx, client/src/components/SpreadLayouts/SixSpokesUpright.jsx, client/src/components/SpreadLayouts/ThreeCardHorizontal.jsx, client/src/utils/CardUtils.js, server/models/Reading.js, server/schemas/resolvers.js
**Description**  
Added functionality to display "Eclipsed" for reversed cards in the "Eclipse of the Soul Tarot" deck. Refactored spread layouts to centralize card rotation logic via a utility function, `getCardRotation`. The following updates were made:
- Updated the backend resolver to include the deck name for determining orientation logic.
- Added a utility function to centralize rotation logic for decks with special behaviors.
- Refactored spread layouts (`SixSpokesUpright`, [other layouts]) to use the utility function instead of inline logic.
This ensures that reversed cards in the "Eclipse of the Soul Tarot" deck are correctly labeled as "Eclipsed" and displayed consistently across layouts. Centralizing rotation logic in a utility function improves maintainability and makes it …
=> Add "Eclipsed" logic for EOTS deck and refactor layouts 

client/src/components/AppElements/MainContainer.jsx
**Title: **
BugFix: MainContainer
***Description:***
I fixed the issue with themes. The isPublicInfoPages class is overwritten. It now checks if the user is logged in to set the class.
** PR Checklist:** 
[x] Code follows the project's coding standards and conventions. 
[x] The code formatter was run before submitting PR, and if needed, changes were made before submitting the PR request. 
[ ] Jira tasks added in the project backlog to update documentation if necessary. 
[ ] (add any other checklist items discussed in sprint planning or subtasks in story) 
**Behavior:** 
- **User Side Behavior:** 
[x] User should now see their theme on every page when logged in
=> bugFix(MainContainer): user now sees themes when logged in on all pages
